// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC12SugZX8SxdR_CwJMy_CP8k7HlvbDTuk',
    appId: '1:468408385936:web:0bf2e60d5c318a182cb315',
    messagingSenderId: '468408385936',
    projectId: 'musicapp-f8971',
    authDomain: 'musicapp-f8971.firebaseapp.com',
    storageBucket: 'musicapp-f8971.firebasestorage.app',
    measurementId: 'G-Y12Q5ECV67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzsyUFHV6fhI1MmLqjAqrYO_2TYjGauPA',
    appId: '1:468408385936:android:97b60c09262bd8f72cb315',
    messagingSenderId: '468408385936',
    projectId: 'musicapp-f8971',
    storageBucket: 'musicapp-f8971.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXQ9evtbvGIo1QY4yiWBqx8cil2c3Yf2M',
    appId: '1:468408385936:ios:7db0b751594f763e2cb315',
    messagingSenderId: '468408385936',
    projectId: 'musicapp-f8971',
    storageBucket: 'musicapp-f8971.firebasestorage.app',
    iosBundleId: 'com.example.appMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXQ9evtbvGIo1QY4yiWBqx8cil2c3Yf2M',
    appId: '1:468408385936:ios:7db0b751594f763e2cb315',
    messagingSenderId: '468408385936',
    projectId: 'musicapp-f8971',
    storageBucket: 'musicapp-f8971.firebasestorage.app',
    iosBundleId: 'com.example.appMusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC12SugZX8SxdR_CwJMy_CP8k7HlvbDTuk',
    appId: '1:468408385936:web:f8563f65aadbf6982cb315',
    messagingSenderId: '468408385936',
    projectId: 'musicapp-f8971',
    authDomain: 'musicapp-f8971.firebaseapp.com',
    storageBucket: 'musicapp-f8971.firebasestorage.app',
    measurementId: 'G-VQLG88P5DH',
  );
}
