// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCS3gR3bl7rDbKK_RBWEHJWaHzHnCGSU4',
    appId: '1:715032422450:web:b6eceffd492523d1ec742b',
    messagingSenderId: '715032422450',
    projectId: 'belle-music-app',
    authDomain: 'belle-music-app.firebaseapp.com',
    storageBucket: 'belle-music-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASjkKMWOh3UXAXorWdYsXyCYYz7AtAfdY',
    appId: '1:715032422450:android:f5f7b02cf26591e9ec742b',
    messagingSenderId: '715032422450',
    projectId: 'belle-music-app',
    storageBucket: 'belle-music-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCejbty7Zm6rCPnimovsnAZM5ik64_wbMA',
    appId: '1:715032422450:ios:111732e0d90cc8a6ec742b',
    messagingSenderId: '715032422450',
    projectId: 'belle-music-app',
    storageBucket: 'belle-music-app.firebasestorage.app',
    androidClientId: '715032422450-i2cnp23v2bjha78656ldif5vucuq0env.apps.googleusercontent.com',
    iosClientId: '715032422450-63j0uuuvou5r9cfi7t1e08tjqgtqh5uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCejbty7Zm6rCPnimovsnAZM5ik64_wbMA',
    appId: '1:715032422450:ios:111732e0d90cc8a6ec742b',
    messagingSenderId: '715032422450',
    projectId: 'belle-music-app',
    storageBucket: 'belle-music-app.firebasestorage.app',
    androidClientId: '715032422450-i2cnp23v2bjha78656ldif5vucuq0env.apps.googleusercontent.com',
    iosClientId: '715032422450-63j0uuuvou5r9cfi7t1e08tjqgtqh5uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCS3gR3bl7rDbKK_RBWEHJWaHzHnCGSU4',
    appId: '1:715032422450:web:0eaadaa9fe1ba7a6ec742b',
    messagingSenderId: '715032422450',
    projectId: 'belle-music-app',
    authDomain: 'belle-music-app.firebaseapp.com',
    storageBucket: 'belle-music-app.firebasestorage.app',
  );

}